---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marufh
  namespace: default
  labels:
    app: marufh
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: marufh
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marufh
    spec:
      containers:
      - image: eu.gcr.io/marufh/marufh:1.0.0
        imagePullPolicy: Always
        name: marufh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
